[workspace]
members = [
    "sentry",
    "sentry-actix",
    "sentry-backtrace",
    "sentry-core",
    "sentry-error-chain",
    "sentry-failure",
    "sentry-log",
    "sentry-panic",
    "sentry-types",
]
